# Tensorflow 버전 확인

In [2]:
!pip install tensorflow

  Obtaining dependency information for tensorflow from https://files.pythonhosted.org/packages/e4/14/d795bb156f8cc10eb1dcfe1332b7dbb8405b634688980aa9be8f885cc888/tensorflow-2.16.1-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for tensorflow-intel==2.16.1 from https://files.pythonhosted.org/packages/e0/36/6278e4e7e69a90c00e0f82944d8f2713dd85a69d1add455d9e50446837ab/tensorflow_intel-2.16.1-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for absl-py>=1.0.0 from https://files.pythonhosted.org/packages/a2/ad/e0d3c824784ff121c03cc031f944bc7e139a8f1870ffd2845cc2dd76f6c4/absl_py-2.1.0-py3-none-any.whl.metadata
  Obtaining dependency information for astunparse>=1.6.0 from https://files.pythonhosted.org/packages/2b/03/13dde6512ad7b4557eb792fbcf0c653af6076b81e5941d36ec61f7ce6028/astunparse-1.6.3-py2.py3-none-any.whl.metadata
  Obtaining dependency information for flatbuffers>=23.5.26 from https://files.pythonhosted.org/packages/bf/45/c961e3cb6ddad76b3

In [3]:
import tensorflow  as tf
print(tf.__version__)

2.16.1


## 데이터 생성 및 접근

In [4]:
tf.constant(42)

t = tf.constant([[1, 2, 3], [4, 5, 6]])
print(t)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [11]:
print(t[:, 1]) # 1번째 열 : 하나의 열이라서 1차원 배열
print(t[:, 1 :]) # 1번째 열부터 모든 열
print(t[:, 1, tf.newaxis]) # 데이터를 분할한 후 새로운 축으로 만들어서 출력
# 1차원 배열이 2차원 배열이 됩니다.

tf.Tensor([2 5], shape=(2,), dtype=int32)
tf.Tensor(
[[2 3]
 [5 6]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2]
 [5]], shape=(2, 1), dtype=int32)


## 연산

In [12]:
print(t + 10) # broadcast 연산

tf.Tensor(
[[11 12 13]
 [14 15 16]], shape=(2, 3), dtype=int32)


In [13]:
print(tf.square(t))

tf.Tensor(
[[ 1  4  9]
 [16 25 36]], shape=(2, 3), dtype=int32)


In [14]:
tf.transpose(t) @ t

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])>

###  tensor 와  ndarray 변환

In [16]:
import numpy as np
ar = np.array([2, 3, 4])
print(tf.constant(ar))

tf.Tensor([2 3 4], shape=(3,), dtype=int32)


In [17]:
print(tf.constant(ar).numpy)
print(np.array(ar))

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4])>>
[2 3 4]


### 타입 변환

In [ ]:
# ndarray 는 이렇게 자료형이 다른 경우 자동으로 자료형으 변경해서
#  

print(tf/constant(2.0) + tf.constant(40))

In [ ]:
t1 = tf.constant(40)
# 형 변환 한 후 연산 수행
print(tf.constant(2.0) + tf.cast(t1, tf.flosae32)

In [29]:
# 변수 생성
v = tf.Variable([[1, 2, 3], [4, 5, 6 ]])
print(v)
print(id(v))
# 이 경우는 데이터를 수정한 것이 아니고
# 기존 데이터를 복제해서 연산을 수행한 후 그 결과를 가리키도록 한 것
# 참조하는 위치가 변경됨
v = v * 2
print(v)
print(id(v))

# 내부 데이터 수정
v = tf.Variable([[1, 2, 3], [4, 5, 6]])
print(v)
print(id(v))
# 이경우는 id 변경 없이 데이터를 수정
v.assign(2 * v)
print(v)
print(id(v))

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>
2101458531088
tf.Tensor(
[[ 2  4  6]
 [ 8 10 12]], shape=(2, 3), dtype=int32)
2101458625536
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>
2101429254608
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]])>
2101429254608


### Tensorflow 함수

In [30]:
def cube (x) :
    return x ** 3
print(cube)

tf.cube = tf.function(cube)
print(tf.cube)

<function cube at 0x000001E948AEF740>


In [31]:
@tf. function # decorator 를 이용한 텐서플ㄹ로우 함수 생성
def cube (x) :
    return x ** 3
print(cube)

tf.cube = tf.function(cube)
print(tf.cube)

## 뉴런을 직접 생성

In [33]:
# 시그모이드
import math
def sigmoid(x) :
    return 1 / (1 + math.exp(-x))

# 입력
x = 1

# 출력 
y = 0

# 한 번 학습
w = tf.random.normal([1], 0, 1)
output = sigmoid(x * w)
print(output)

0.36894579369022124


In [36]:
# 학습률을  0.01 로 설정해서 경사하강법을 수행

# 학습 회수 - epoch
for i in range(100000) :
    # 출력을 생성
    output = sigmoid(x*w)
    # 출력 오차를 계산
    error = y - output
    
    # 가중치 업데이트
    w = w + x * 0.1 * error
    
    # 횟수와 오차 그리고 출력값을 확인
    if i % 10000 == 0:
        print(i, error, output)

0 -0.0009938039908116898 0.0009938039908116898
10000 -0.0004986076413431857 0.0004986076413431857
20000 -0.00033275999998548354 0.00033275999998548354
30000 -0.0002497039473000715 0.0002497039473000715
40000 -0.00019983714110252492 0.00019983714110252492
50000 -0.00016651728589958426 0.00016651728589958426
60000 -0.00014280855781084072 0.00014280855781084072
70000 -0.0001249788821151294 0.0001249788821151294
80000 -0.0001110612022668561 0.0001110612022668561
90000 -9.9918597794114e-05 9.9918597794114e-05


In [38]:
# 입력
x = 0

# 출력
y = 1

# 가중치
w = tf.random.normal([1], 0, 1)
# 편향 생성
b = tf.random.normal([1], 0, 1)

# 학습률을  0.01 로 설정해서 경사하강법을 수행

# 학습 회수 - epoch
for i in range(1000) :
    # 출력을 생성
    output = sigmoid(x*w)
    # 출력 오차를 계산
    error = y - output
    
    # 가중치 업데이트
    w = w + x * 0.1 * error
    
    # 횟수와 오차 그리고 출력값을 확인
    if i % 100 == 0:
        print(i, error, output)

0 0.5 0.5
100 0.5 0.5
200 0.5 0.5
300 0.5 0.5
400 0.5 0.5
500 0.5 0.5
600 0.5 0.5
700 0.5 0.5
800 0.5 0.5
900 0.5 0.5


## 기울기 소실을 막기 위해 편향 추가

In [37]:
# 입력
x = 0

# 출력
y = 1

# 가중치
w = tf.random.normal([1], 0, 1)
# 편향 생성
b = tf.random.normal([1], 0, 1)


# 학습률을  0.01 로 설정해서 경사하강법을 수행

# 학습 회수 - epoch
for i in range(1000) :
    # 출력을 생성
    output = sigmoid(x*w + 1 *b)
    # 출력 오차를 계산
    error = y - output
    
    # 가중치 업데이트
    w = w + x * 0.1 * error
    # 편향 업데이트
    b = b + 1 * 0.1 * error
    
    # 횟수와 오차 그리고 출력값을 확인
    if i % 100 == 0:
        print(i, error, output)

0 0.8965136528568959 0.10348634714310408
100 0.138466668269424 0.861533331730576
200 0.06112730932988841 0.9388726906701116
300 0.038611250073897097 0.9613887499261029
400 0.028100536249925256 0.9718994637500747
500 0.02205070895054806 0.9779492910494519
600 0.018129091498460426 0.9818709085015396
700 0.015384326290363126 0.9846156737096369
800 0.013357378740702086 0.9866426212592979
900 0.011800002079861094 0.9881999979201389


## AND 연산 구현

In [42]:
X = np.array([[0,0],[1,0],[0,1],[1,1]])
y = np.array([[0], [0], [0], [1]])

# 가중치 초기화
w = tf.random.normal([2], 0, 1) # 입력 피처가 두개이므로 가중치도 2개
b = tf.random.normal([1], 0, 1) # 편향

# 학습
for  i in range(10000) :
    # 샘플이 여러개 이므로 에러는 모든 샘플의 에러 합계로 계산
    # 에러 합계를 저장할 변수
    error_sum = 0
    # 4는 입력데이터의 개수
    for j in range(4) :
        # 출력
        output = sigmoid(np.sum(X[j] * w) + 1 * b)
        # 오차
        error = y[j][0] - output
        #가중치 업데이트 - 학습률은 0.1
        w = w + X[j] * 0.1 * error
        # 편향 업데이트
        b = b + 1 * 0.1 * error
        # 에러 값을 추가
        error_sum += error
        
    if i % 500 == 0 :
        print("{0}번째 : {1}".format(i, error_sum))
        

0번째 : -1.8083692187041893
500번째 : -0.05493090903540032
1000번째 : -0.02945548397268294
1500번째 : -0.020001727182268114
2000번째 : -0.015104003570034746
2500번째 : -0.012121171339144796
3000번째 : -0.010113141290788552
3500번째 : -0.008674615784162482
4000번째 : -0.0075926647176273385
4500번째 : -0.0067489868782883156
5000번째 : -0.0060731991866418596
5500번째 : -0.0055196329334024595
6000번째 : -0.005058541975741442
6500번째 : -0.004668205586768077
7000번째 : -0.004333426277246984
7500번째 : -0.0040435144550475186
8000번째 : -0.003789853965702245
8500번째 : -0.0035660393308939425
9000번째 : -0.0033670059053252446
9500번째 : -0.0031891707948678016


In [43]:
# 예측한 값 확인
for i in range(4) :
    print('X : ', X[i], 'y :', y[i], sigmoid(np.sum(X[i] * w) + b))

X :  [0 0] y : [0] 1.82917095206161e-07
X :  [1 0] y : [0] 0.00504750425528397
X :  [0 1] y : [0] 0.005050685399297795
X :  [1 1] y : [1] 0.9929472765312585


## XOR 문제

In [44]:
X = np.array([[0,0],[1,0],[0,1],[1,1]])
y = np.array([[0], [1], [1], [0]])

# 가중치 초기화
w = tf.random.normal([2], 0, 1) # 입력 피처가 두개이므로 가중치도 2개
b = tf.random.normal([1], 0, 1) # 편향

# 학습
for  i in range(10000) :
    # 샘플이 여러개 이므로 에러는 모든 샘플의 에러 합계로 계산
    # 에러 합계를 저장할 변수
    error_sum = 0
    # 4는 입력데이터의 개수
    for j in range(4) :
        # 출력
        output = sigmoid(np.sum(X[j] * w) + 1 * b)
        # 오차
        error = y[j][0] - output
        #가중치 업데이트 - 학습률은 0.1
        w = w + X[j] * 0.1 * error
        # 편향 업데이트
        b = b + 1 * 0.1 * error
        # 에러 값을 추가
        error_sum += error
        
    if i % 500 == 0 :
        print("{0}번째 : {1}".format(i, error_sum))
        

0번째 : 1.6925100789796375
500번째 : -9.631906816687241e-06
1000번째 : -6.980329025907395e-08
1500번째 : -6.980329025907395e-08
2000번째 : -6.980329025907395e-08
2500번째 : -6.980329025907395e-08
3000번째 : -6.980329025907395e-08
3500번째 : -6.980329025907395e-08
4000번째 : -6.980329025907395e-08
4500번째 : -6.980329025907395e-08
5000번째 : -6.980329025907395e-08
5500번째 : -6.980329025907395e-08
6000번째 : -6.980329025907395e-08
6500번째 : -6.980329025907395e-08
7000번째 : -6.980329025907395e-08
7500번째 : -6.980329025907395e-08
8000번째 : -6.980329025907395e-08
8500번째 : -6.980329025907395e-08
9000번째 : -6.980329025907395e-08
9500번째 : -6.980329025907395e-08


In [45]:
# 예측한 값 확인
for i in range(4) :
    print('X : ', X[i], 'y :', y[i], sigmoid(np.sum(X[i] * w) + b))

X :  [0 0] y : [0] 0.5128177040587629
X :  [1 0] y : [1] 0.5000000363215804
X :  [0 1] y : [1] 0.48718236853665897
X :  [1 1] y : [0] 0.4743815336379531


In [46]:
# 가중치와 편향을 출력
print('가중치 :', w)
print('편향 :', b)

# 

가중치 : tf.Tensor([-0.05128191 -0.10256381], shape=(2,), dtype=float32)
편향 : tf.Tensor([0.05128205], shape=(1,), dtype=float32)
